name: cambi_ar_app
description: "A new Flutter project."
publish_to: 'none' # Private package, remove if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI Components & Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1  # Recommended for efficient state management

  # Navigation
  go_router: ^14.8.1  # Structured route management with deep linking

  # HTTP & Networking
  dio: ^5.8.0+1  # Advanced HTTP client for API calls

  # JSON Serialization & Freezed Models
  json_serializable: ^6.9.4  # Auto-generate JSON code
  freezed_annotation: ^3.0.0  # Data classes with Freezed

  # Database & Persistence
  drift: ^2.25.1  # SQLite ORM in Dart
  sqlite3_flutter_libs: ^0.5.31  # Required for Drift
  hive: ^2.2.3  # Lightweight NoSQL database
  hive_flutter: ^1.1.0  # Flutter bindings for Hive
  firebase_core: ^3.12.1  # Firebase SDK core
  cloud_firestore: ^5.6.5  # Firebase Firestore database

  # Authentication & Security
  firebase_auth: ^5.5.1  # Firebase authentication
  # flutter_secure_storage: ^9.2.4  # Secure storage for sensitive data

  # Date, Currency, Formatting
  intl: ^0.20.2  # Internationalization and formatting
  # flutter_currency_formatte  # Currency formatting

  # UI Enhancements
  flutter_slidable: ^4.0.0  # Swipe actions in lists
  flutter_expandable_fab: ^2.3.0  # Expandable Floating Action Button
  syncfusion_flutter_charts: ^28.2.7  # Charts & data visualization

  # Utility & Hooks
  flutter_hooks: ^0.21.2  # Enhances stateful widgets with hooks

  # Notifications
  firebase_messaging: ^15.2.4  # Push notifications

  # Logging & Debugging
  logger: ^2.5.0  # Structured logging tool

  # Background Tasks
  workmanager: ^0.5.2  # Background processing tasks


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^5.0.0  # Recommended lint rules

  # Build Tools
  build_runner: ^2.4.15  # Required for code generation
  freezed: ^3.0.2  # Data class generator
  json_serializable: ^6.9.4  # Auto JSON conversion

flutter:
  uses-material-design: true

  # # Asset Management
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/

  # # Custom Fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
